#include "enumTest.idl"
#include "seqTest.idl"
#include "stringTest.idl"

struct Test {
    long test_long; //@key
    TestEnum test_enum;
    StringTest test_string;
    SeqTest test_seq;
};//@Extensibility FINAL_EXTENSIBILITY
