#!/bin/ksh

# (c) 2005-2016  Copyright, Real-Time Innovations, Inc.  All rights reserved.
# Permission to modify and use for internal purposes granted.
# This software is provided "as is", without warranty, express or implied.

# You can override the following settings with the correct location of Java
JAVA=`which java`

# Make sure JAVA and NDDSHOME are set correctly
test -z "$JAVA" && echo "java not found" && exit 0
test -z "$NDDSHOME" && echo "NDDSHOME environment variable not set!" && exit 0
test -z "$RTI_PERFTEST_ARCH" && echo "RTI_PERFTEST_ARCH environment variable not set!" && exit 0

# Attempt to set LD_LIBRARY_PATH from which to load native libraries.
# If RTI_PERFTEST_ARCH is set (e.g. to i86Linux2.6gcc4.1.1), you don't
# have to separately set the LD_LIBRARY_PATH.
export LD_LIBRARY_PATH=${NDDSHOME}/lib/${RTI_PERFTEST_ARCH}:${LD_LIBRARY_PATH}

java -Xmx1500m \
     -cp bin/Release/perftestdds.jar:$NDDSHOME/lib/java/nddsjava.jar \
     com.rti.perftest.ddsimpl.PerfTestLauncher \
     $@
