#include "enumTest.idl"
#include "seqTest.idl"
#include "stringTest.idl"

struct Test {
    long test_long;
    PrimitiveEnum test_enum;
    SeqTest seqTest;
    StringTest stringTest;
};//@Extensibility FINAL_EXTENSIBILITY